### ISSUE TITLE
Alternative colour for Other?

### ISSUE THREAD

**Issue by madwort** [inglesp/apogee#34]
Perhaps light grey...?

<img width="713" alt="Screenshot 2024-07-02 at 13 12 00" src="https://github.com/inglesp/apogee/assets/2082895/3b9059de-1c82-450a-87f9-29b7d7118b35">

**Comment by madwort** [comment]
or even just some outlining?

**Comment by inglesp** [comment]
Thanks -- I'll address this tonight
